name: Atualizar Idade Portfólio

on:
  schedule:
    - cron: "0 0 25 7 *" # Executa à meia-noite (UTC) todo dia 25 de julho
  workflow_dispatch: # Permite executar manualmente também

permissions:
  contents: write

jobs:
  update-age:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Calcular nova idade e atualizar Portfólio
        run: |
          #!/bin/bash
          DATA_NASC="1996-07-25"
          HOJE=$(date +%Y-%m-%d)

          ANO_ATUAL=$(date -d "$HOJE" +%Y)
          MES_DIA_ATUAL=$(date -d "$HOJE" +%m%d)
          ANO_NASC=$(date -d "$DATA_NASC" +%Y)
          MES_DIA_NASC=$(date -d "$DATA_NASC" +%m%d)

          IDADE=$((ANO_ATUAL - ANO_NASC))
          if [[ "$MES_DIA_ATUAL" -lt "$MES_DIA_NASC" ]]; then
            IDADE=$((IDADE - 1))
          fi

          echo "Idade calculada: $IDADE"

          sed -i "s/<!-- idade -->.*<!-- \/idade -->/<!-- idade -->$IDADE<!-- \/idade -->/" about.html

      - name: Commit e push se houver alterações
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add about.html
          git commit -m "Atualiza idade automaticamente" || exit 0
          git push
